[package]
name = "db-rust"
version = "0.1.0"
authors = ["incker <sagan.stanislav@gmail.com>"]
edition = "2018"

[dependencies]
rocksdb = "0.11.0"
criterion = "0.2.9"
event_store = { git = "https://github.com/incker/rust-event-storage-lib"}