[package]
name = "event_log_store"
version = "0.1.0"
authors = ["incker <sagan.stanislav@gmail.com>"]
edition = "2018"

[dependencies]

[dev-dependencies]
criterion = "0.2.10"
rocksdb = "0.11.0"
lockfile = "0.2.1"

[[bench]]
name = "store_bench"
harness = false